name: Bump static files version

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          export PREVIOUS_VERSION="`echo .version`"
          export NEW_VERSION="`git rev-parse --short HEAD`"
          
          find . -type f -exec sed -i "s/_slakje_version=${PREVIOUS_VERSION}/_slakje_version={NEW_VERSION}/g" {} +
          
          echo $NEW_VERSION > .version
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] bump static files version"
          git push
